version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_CORS_ORIGIN=*
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama-data:/root/.ollama
    expose:
      - "11434"
    networks:
      - internal
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: service:ollama
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY} # Place your authkey in a .env file or replace directly
      - TS_EXTRA_ARGS=--hostname=${OLLAMA_HOSTNAME}
      - TS_ROUTES=0.0.0.0/0
    depends_on:
      - ollama

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - internal
    depends_on:
      - ollama

volumes:
  ollama-data:
  tailscale-data:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
