services:
  proxy-server:
    build: .
    container_name: bun-proxy-server
    ports:
      - "17102:17102"
    environment:
      - PORT=17102
    networks:
      - tailscale-net

  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: service:proxy-server
    volumes:
      - tailscale-var-lib:/var/lib
      - /dev/net/tun:/dev/net/tun
      - ../config:/config
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}  # Set this in your .env or environment
      - TS_EXTRA_ARGS=--hostname=${TS_HOSTNAME}
      - TS_SERVE_CONFIG=../config/https.json
      - TS_STATE_DIR=/var/lib/tailscale

volumes:
  tailscale-var-lib:

networks:
  tailscale-net:
    driver: bridge